env: local

http:
  protocol: http
  url: localhost
  port: 3000
  cors:
    maxage: 0

postgres:
  host: localhost
  port: 5432
  user: root
  password: 123456
  database: pgdb
  sslmode: disable

sqlite:
  path: internal/sqlite.db

# openssl rand -base64 172 | tr -d '\ n'
jwt:
  secret: 9bt7EMA3BEu6QwRPTE4Vzwg2486U5cSlNCt0PF1YFA2Crua5hoPA2RFgeBl39OlPGMsweg5adc3KAiev3q94vLJtwRYRPbPw5
  expires: 3600

pagination:
  limit: 10
