### Регистрация пользователя
POST http://127.0.0.1:3000/v1/signup
content-type: application/json
accept-language: ru

{
    "first_name": "Robin",
    "last_name": "Good",
    "email": "some@user.org",
    "password": "123",
    "password_confirm": "123"
}
